// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ASD_CHARACTERTYPES_H
#define ASD_CHARACTERTYPES_H

/************************************************************
 CharacterTypes class header
 ************************************************************/

#include <CodeFromUML/Pkg_asd.h>
#include <cstdlib>
#include <ctime>
#include <iostream>
#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace CodeFromUML {

/************************************************************/
/**
 * 
 */
class CharacterTypes {
public:
	CharacterTypes() : // @suppress("Class members should be properly initialized")
			healcounter(0) {
		srand(time(0));
	}
	virtual ~CharacterTypes(){}
	/**
	 * 
	 */
	virtual void attack() = 0;

	/**
	 * 
	 */
	virtual void heal() = 0;

	/**
	 * 
	 */
	bool isAlive();

protected:

	/**
	 * 
	 */
	::PrimitiveTypes::Integer HP;

	/**
	 * 
	 */
	::PrimitiveTypes::Integer healcounter;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace asd

/************************************************************
 End of CharacterTypes class header
 ************************************************************/

#endif
