// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define asd_CharacterTypes_BODY

/************************************************************
 CharacterTypes class body
 ************************************************************/

// include associated header file
#include <CodeFromUML/CharacterTypes.h>

// Derived includes directives

namespace CodeFromUML {

// static attributes (if any)

/**
 * 
 */
bool CharacterTypes::isAlive() {
	return HP > 0;
}

} // of namespace asd

/************************************************************
 End of CharacterTypes class body
 ************************************************************/
