// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ASD_MAGE_H
#define ASD_MAGE_H

/************************************************************
 Mage class header
 ************************************************************/

#include <CodeFromUML/CharacterTypes.h>
#include <CodeFromUML/Pkg_asd.h>

namespace CodeFromUML {

/************************************************************/
/**
 * 
 */
class Mage: public CharacterTypes {
public:
	Mage();
	/**
	 * 
	 */
	void attack();

	/**
	 * 
	 */
	void heal();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace asd

/************************************************************
 End of Mage class header
 ************************************************************/

#endif
