// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ASD_WARRIOR_H
#define ASD_WARRIOR_H

/************************************************************
 Warrior class header
 ************************************************************/

#include <CodeFromUML/CharacterTypes.h>
#include <CodeFromUML/Pkg_asd.h>

namespace CodeFromUML {

/************************************************************/
/**
 * 
 */
class Warrior: public CharacterTypes {
public:
	Warrior();
	/**
	 * 
	 */
	void attack();

	/**
	 * 
	 */
	void heal();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace asd

/************************************************************
 End of Warrior class header
 ************************************************************/

#endif
