// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define asd_Mage_BODY

/************************************************************
 Mage class body
 ************************************************************/

// include associated header file
#include <CodeFromUML/Mage.h>
using std::cout;
using std::cin;
using std::endl;
// Derived includes directives

namespace CodeFromUML {

// static attributes (if any)

Mage::Mage()
{
	HP = 120;
}

/**
 * 
 */
void Mage::attack() {
	if(rand()%10 > 7)
	{
		int dmg = rand()%5 + 1;
		HP -= dmg;
		std::cout << "Legyőzted a katonát, de megsérültél.\nAktuális életerő: " << HP << std::endl;
		healcounter++;
	}
	else
	{
		cout << "Karcolás nélkül legyőzted a katonát." << endl;
		healcounter++;
	}
}

/**
 * 
 */
void Mage::heal() {
	if(healcounter < 8)
	{
		cout << "Ehhez még " << 8 - healcounter << " kört kell várnod." << endl;
	}
	else
	{
		int hpHeal = rand()%20 + 11;
		HP += hpHeal;
		cout << hpHeal << " életerőt gyógyítottál magadon.\nAktuális életerő: " << HP << endl;
		healcounter = 0;
	}
}

} // of namespace asd

/************************************************************
 End of Mage class body
 ************************************************************/
